blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'

urlpatterns = [
    path('poster', post, name='poster'),
    path('liker/<int:pk>', liker, name='liker'),
]

compte/urls.py
from django.urls import path
from.views import *

app_name = 'compte'
urlpatterns = [
    path('<slug>/profile', ProfileView.as_view(), name='profile'),
    path('<slug>/profile/update', ProfileView.update_profile, name='profile_update'),
    path('<int:pk>/suivre', suivre, name='suivre'),
    path('<int:pk>/forget', abandonner, name='forget'),
    path('profile-suggestions', ProfileListView.as_view(), name='profile_list'),
    path('notifcations', NoteListView.as_view(), name='note_list'),
]

dyday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from compte.views import WelcomeView, InscriptionView, HomeView, connection, deconnection


urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('inscription/', InscriptionView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='home'),
    path('membre/', include('compte.urls', namespace='compte')),
    path('membre/', include('blog.urls', namespace='blog')),
    path('logout/', deconnection, name='logout'),
    path('login/', connection, name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compte/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify



class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=100, null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars', default='avatars/default.jpg',null=True, blank=True)
    info = models.TextField(null=True, blank=True, help_text="Informations sur vous")
    address = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    abonnes = models.ManyToManyField(User, related_name='abonnements')
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        return super(Profile, self).save(*args, **kwargs)


class NotificationBox(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='notebox')
    notifications = models.ManyToManyField('Notification', related_name='box', null=True, blank=True)

    def __str__(self):
        return f" NotificationBox ({self.user.username})"


class Notification(models.Model):
    text = models.TextField()
    link = models.URLField(null=True)
    lue = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.link

    class Meta:
        ordering = ['-time']

compte/forms.py
from django import forms
from .models import Profile, User


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        fields = ['avatar', 'contact', 'info', 'address']
        model = Profile
        labels = {
            'info':'Information sur vous',
            'avatar':'Photo de profile',
        }


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput
        }


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

compte/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View, generic
from .forms import UserCreationForm, ProfileCreationForm, LoginForm
from django.contrib.auth import login, logout, authenticate, mixins
from .models import Profile, User, NotificationBox, Notification
from blog.models import SimplePost


class WelcomeView(generic.TemplateView):
    template_name = 'welcome.html'


class InscriptionView(View):
    template_name = 'compte/inscription.html'
    form = UserCreationForm

    def get(self, request, *args, **kwargs):
        form = self.form
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        print("Entrez: InscriptionView::post")
        if form.is_valid():
            user = User.objects.create(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email']
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            profile = Profile.objects.create(user=user)
            NotificationBox.objects.create(user=user).save()
            profile.save()
            login(request, user)
            return redirect('compte:profile', profile.slug)
        return render(request, self.template_name, locals())


class HomeView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = 'home.html'
    login_url = 'welcome'

    def get_context_data(self, **kwargs):
        data = super(HomeView, self).get_context_data(**kwargs)
        data['postes'] = SimplePost.objects.all()
        return data


class ProfileView(mixins.LoginRequiredMixin, generic.DetailView):
    login_url = 'welcome'
    model = Profile
    context_object_name = 'profile'
    template_name = 'compte/profile.html'

    def get_context_data(self, **kwargs):
        data = super(ProfileView, self).get_context_data(**kwargs)
        data['update_form'] = ProfileCreationForm
        data['update_form'].instance = self.get_object()
        return data

    @staticmethod
    def update_profile(request, slug,  *args, **kwargs):
        form = ProfileCreationForm(request.POST, request.FILES)
        profile = get_object_or_404(Profile, slug=slug)
        if form.is_valid():
            profile.contact = form.cleaned_data['contact']
            profile.info = form.cleaned_data['info']
            profile.avatar = form.cleaned_data['avatar']
            profile.address = form.cleaned_data['address']
            profile.save()
        return redirect('compte:profile', profile.slug)


def deconnection(request):
    logout(request)
    return redirect('welcome')

def connection(request):
    error = None
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('home')
            else: error = True
    else:
        form = LoginForm
    return render(request, 'compte/login.html', locals())

def suivre(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    profile.abonnes.add(request.user)
    notext = f"{request.user.username.title()} à commencer a suivre {profile.user.username}"
    note = Notification(text=notext)
    note.save()
    request.user.notebox.notifications.add(note)
    profile.user.notebox.notifications.add(note)
    next = request.GET['next'] if 'next' in request.GET else 'home'
    return redirect(next)

def abandonner(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    profile.abonnes.remove(request.user)
    next = request.GET['next'] if 'next' in request.GET else 'home'
    return redirect(next)


class ProfileListView(generic.ListView):
    template_name = 'compte/profile_list.html'
    model = Profile
    context_object_name = 'profiles'

    def get_queryset(self):
        return Profile.objects.difference(self.request.user.abonnements.all())


class NoteListView(generic.ListView):
    template_name = 'compte/note_list.html'
    model = Notification
    queryset = Notification.objects.all()
    context_object_name = 'notes'

    def get_queryset(self):
        queryset = super(NoteListView, self).get_queryset()
        for profile in self.request.user.abonnements.all():
            queryset.union(queryset, profile.user.notebox.notifications.all()).order_by('-time')

        return queryset

templates/compte/inscription.html
{% extends 'base.html' %}

{% load static %}

{% block base-body %}
<div class="container mt-3">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="white border">
                <div class="border-bottom p-3">
                    <a href="{% url 'welcome' %}" class="p-1 rounded-circle bg-info white-text"><span class="fa fa-arrow-left"></span></a>
                    <span class="grey-text">INSCRIVEZ-VOUS</span>
                </div>
                <div class="p-3">
                    {% if form.has_error %}
                        <div class="alert alert-danger">
                        {% for error in form.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}

                        </div>
                    {% endif %}
                    <form action="{% url 'signup' %}" method="post" class="grey-text">

                        {% csrf_token %}

                        {{ form.as_p }}
                        <div class="d-flex justify-content-between align-items-center">
                            <button class="btn btn-info btn-sm" type="submit">S'inscrire'</button>
                            <a href="{% url 'login' %}" class="grey-text font-weight-bold">Je veux me connecter</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/compte/login.html
{% extends 'base.html' %}

{% load static %}

{% block base-body %}
<div class="container mt-3">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="white border">
                <div class="border-bottom p-3">
                    <a href="{% url 'welcome' %}" class="p-1 rounded-circle bg-info white-text"><span class="fa fa-arrow-left"></span></a>
                    <span class="grey-text">INSCRIVEZ-VOUS</span>
                </div>
                <div class="p-3">
                    {% if form.has_error or error %}
                        <div class="alert alert-danger">
                        {% for error in form.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                        <p class="font-weight-bold">Nom d'utilisateur ou mot de passe incorrecte !</p>
                        </div>
                    {% endif %}
                    <form action="{% url 'login' %}" method="post" class="grey-text">

                        {% csrf_token %}

                        {{ form.as_p }}
                        <div class="d-flex justify-content-between align-items-center">
                            <button class="btn btn-info btn-sm" type="submit">Se connecter'</button>
                            <a href="{% url 'signup' %}" class="grey-text font-weight-bold">Je veux m'inscrire</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/compte/note_list.html
{% extends 'home.html' %}

{% load static %}


{% block home-body %}
<div class="col-6">
    <div class="white border p-3">
        <h3 class="grey-text">Vos Notifications</h3>
        <hr>
        <div class="">
            {% for note in notes %}
            <div class="d-flex border p-2 mb-2">
                <div>{{ note.text }}</div>
                <br>
                <small class="text-muted d-block">{{ note.time|timesince }}</small>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

templates/compte/profile.html
{% extends 'home.html' %}


{% block home-body %}
<div class="col-6">
            <div class="white border p-3 mb-3">
                <div class="d-flex">
                    <div class="w-25 text-center">
                        <img src="/medias/{{ profile.avatar }}" height="100" class="rounded-circle border border-info" alt="">
                        <div class="bg-info white-text mt-3 p-2 rounded text-center font-weight-bold">{{ profile.user.username|title }}</div>
                    </div>
                    <div class="flex-grow-1">
                        <div class="nav flex-column grey-text">
                            <span class="nav-link">
                                <span class="fa fa-phone mr-2"></span>
                                <span>{{ profile.contact|default:'Auncun' }}</span>
                            </span>
                            <span class="nav-link">
                                <span class="fa fa-mail-bulk mr-2"></span>
                                <span>{{ profile.user.email|default:'Auncun' }}</span>
                            </span>
                            <span class="nav-link">
                                <span class="fa fa-location-arrow mr-2"></span>
                                <span>{{ profile.address|default:'Auncun' }}</span>
                            </span>
                            <span class="nav-link">
                                <blockquote class="blockquote bq-info ">
                                    <span class="fa fa-quote-left"></span><br>
                                    {{ profile.info|linebreaks }}<span class="fa fa-quote-right">
                                </blockquote>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            {% if request.user.profile == profile %}
            <div class="white border mb-3">
                <div class="border border-bottom p-3">
                    <span class="grey-text">MODIFIER MON PROFILE</span>
                </div>
                <form method="post" enctype="multipart/form-data" action="{% url 'compte:profile_update' profile.slug %}"  class="p-3 grey-text">
                    {% csrf_token %}
                    {{ update_form.as_p }}
                    <p>
                        <button class="btn btn-info btn-sm" type="submit">Modifier</button>
                    </p>
                </form>
            </div>
            {% endif %}
        </div>
{% endblock %}

templates/compte/profile_list.html
{% extends 'home.html' %}

{% load static %}


{% block home-body %}
<div class="col-6">
    <div class="white border p-3">
        <h3 class="grey-text">Profile qui pourrait vous interreser :)</h3>
        <hr>
        <div class="">
            {% for profile in profiles %}
            <div class="d-flex border p-2 mb-2">
                <img width="80" src="/medias/{{ profile.avatar }}" alt="" height="80" class="rounded-circle">
                <div class="flex-grow-1 pl-3">
                    <div><a class="font-weight-bold" href="{% url 'compte:profile' profile.slug %}">{{ profile.user.username|title }}</a></div>
                    <p class="grey-text">{{ profile.info }}</p>
                    <div class="d-flex">
                        <a class="font-weight-bold btn btn-info btn-sm" href="{% url 'compte:suivre' profile.pk %}?next={{ request.path }}"><span class="fa fa-plus"></span> Suivre</a>
                        <a class="font-weight-bold btn btn-info btn-sm" href="{% url 'compte:profile' profile.slug %}"><span class="fa fa-user"></span> Voir le profile</a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}