blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'

urlpatterns = [
    path('poster', post, name='poster'),
    path('liker/<int:pk>', liker, name='liker'),
]

compte/urls.py
from django.urls import path
from.views import *

app_name = 'compte'
urlpatterns = [
    path('<slug>/profile', ProfileView.as_view(), name='profile'),
    path('<slug>/profile/update', ProfileView.update_profile, name='profile_update'),
    path('<int:pk>/suivre', suivre, name='suivre'),
    path('<int:pk>/forget', abandonner, name='forget'),
    path('profile-suggestions', ProfileListView.as_view(), name='profile_list'),
    path('notifcations', NoteListView.as_view(), name='note_list'),
]

dyday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static
from compte.views import WelcomeView, InscriptionView, HomeView, connection, deconnection


urlpatterns = [
    path('admin/', admin.site.urls),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('inscription/', InscriptionView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='home'),
    path('membre/', include('compte.urls', namespace='compte')),
    path('membre/', include('blog.urls', namespace='blog')),
    path('logout/', deconnection, name='logout'),
    path('login/', connection, name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User



class SimplePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    likers = models.ManyToManyField(User, related_name='likes')
    texte = models.TextField(null=True, blank=False,)
    image = models.ImageField(upload_to='posts/images', null=True, blank=True)
    video = models.FileField(upload_to='posts/videos', null=True, blank=True)

    def __str__(self):
        return f"publication de {self.user.username} le {self.time}"

    @property
    def likes(self):
        return self.likers.count()

    @likes.setter
    def likes(self, value):
        pass


class Menace(models.Model):
    destinataire = models.ForeignKey(User, on_delete=models.CASCADE, related_name='menaces')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    time = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Menace sur "+self.destinataire.username

blog/forms.py
from django import  forms
from .models import *


class PostForm(forms.ModelForm):

    class Meta:
        model = SimplePost
        fields = ['texte','image','video']

blog/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View, generic
from .models import *
from .forms import *


class ActualfilView(View):

    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, locals())


def liker(request, pk, **kwargs):
    poste = get_object_or_404(SimplePost, pk=pk)
    if request.user not in poste.likers.all():
        poste.likers.add(request.user)
    else:
        poste.likers.remove(request.user)
    return JsonResponse({'likes': poste.likers.count()})

def post(request, *args, **kwargs):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.instance.user = request.user
        post = form.save()
        post.save()
    return redirect('home')

templates/blog/postview.html
{% for poste in postes %}
<div class="white p-3 border">
    <div class="d-flex align-items-center">
        <img src="/medias/{{ poste.user.profile.avatar }}" height="40" width="40" class="rounded-circle" alt="">
        <div class="ml-2 flex-grow-1">
            <a href="{% url 'compte:profile' poste.user.profile.pk %}" class="font-weight-bold text-info">{{ poste.user.username|title }}</a>
        </div>
        <small class="text-muted">
            il y'a {{ poste.time|timesince }} . <span class="fa fa-globe-africa"></span>
        </small>
    </div>
    <div class="py-1">
        <p>{{ poste.texte }}</p>
    </div>
    <div class="d-flex justify-content-between">
        <div class="nav">
            <a onclick="liker()" class="grey-text px-2"><span class="fa fa-thumbs-up"></span></a>
            <a href="" class="grey-text px-2" data-toggle="collapse" data-target="#comment-collapse-id"><span class="fa fa-comments"></span></a>
            <a href="" class="grey-text px-2"><span class="fa fa-share-alt"></span></a>
        </div>
        <span class="grey-text small font-weight-bold"><span id="nb_likes_{{ poste.pk }}">{{ poste.likers.count }}</span> personnes ont liker</span>
    </div>
    <div class="collapse py-2" id="comment-collapse-id">
        <div class="nav flex-column">
            <div class="nav-item media">
                <img src="assets/img/avatar.jpg" height="35" width="35" class="rounded-circle media-left" alt="">
                <div class="media-body">
                    <a href="" class="font-weight-bold text-info">Annette Doe</a> - <span class="text-muted small">il y 15 min</span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div>
            </div>
        </div>
        <hr>
        <form action="" class="form-inline">
            <textarea placeholder="Commenter cette publication..." name="" id="" cols="30" rows="1" class="grey-text form-control border-0"></textarea>
            <button class="btn btn-sm btn-info">Commenter</button>
        </form>
    </div>
</div>
<script>
    function liker(){
        $.ajax({
            url: '{% url 'blog:liker' poste.pk %}',
            success: function(data){
                alert(data.likes);
            }
        })
    }
    setTimeout(function(){
        $('#nb_likes_{{ poste.pk }}').change('{% url 'blog:liker' poste.pk %}', function (response, statut, xhr) {
            $('#nb_likes_{{ poste.pk }}').html(response.likes);
        });
        console.log(response.likes)
    }, 500);
</script>
{% endfor %}